/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SessionsTypeRouteImport } from './routes/sessions.$type'
import { Route as SubmitTypeRouteImport } from './routes/submit.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsTypeRoute = SessionsTypeRouteImport.update({
  id: '/sessions/$type',
  path: '/sessions/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitTypeRoute = SubmitTypeRouteImport.update({
  id: '/submit/$type',
  path: '/submit/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sessions/$type': typeof SessionsTypeRoute
  '/submit/$type': typeof SubmitTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sessions/$type': typeof SessionsTypeRoute
  '/submit/$type': typeof SubmitTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sessions/$type': typeof SessionsTypeRoute
  '/submit/$type': typeof SubmitTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/sessions/$type' | '/submit/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sessions/$type' | '/submit/$type'
  id: '__root__' | '/' | '/about' | '/sessions/$type' | '/submit/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SessionsTypeRoute: typeof SessionsTypeRoute
  SubmitTypeRoute: typeof SubmitTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$type': {
      id: '/sessions/$type'
      path: '/sessions/$type'
      fullPath: '/sessions/$type'
      preLoaderRoute: typeof SessionsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$type': {
      id: '/submit/$type'
      path: '/submit/$type'
      fullPath: '/submit/$type'
      preLoaderRoute: typeof SubmitTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SessionsTypeRoute: SessionsTypeRoute,
  SubmitTypeRoute: SubmitTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
